### ISSUE TITLE
The “Zentro Restaurant” blueprint does not have the fields to add the URLS of the social links in the Crafter studio.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-restaurant#10]
Description: The “Zentro Restaurant” blueprint does not have the fields to add the URLS of the social links in the Crafter studio.

-Env:
Device: MacBook Pro
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mozilla Firefox 55.0.3 (64-bit)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
1. Open the Crafter studio with the Zentro Restaurant blueprint.
2. Click on the sidebar to display the menu.
3. Expand the component section.
4. On the components section, click on the edit button of the “Contact Us” component.
5. Go to the “Social Links” section 

*Note that the user can add the icon of the social links but can not add the URLS.

CURRENT RESULT: 
==================== 
The “Zentro Restaurant” blueprint does not have the fields to add the URLS of the social links in the Crafter studio.
![social links bug](https://user-images.githubusercontent.com/28119220/31207749-5ca44c9c-a93d-11e7-935e-362066dad291.png)

EXPECTED RESULT: 
==================== 
The “Zentro Restaurant” blueprint should have the fields to add the URLS of the social links in the Crafter studio.

Note this example:
![social media example](https://user-images.githubusercontent.com/28119220/31207753-5fdef7b8-a93d-11e7-95e3-2f8ef27296ec.png)

**Comment by lesalazar93** [comment]
Tested in local environment
