### ISSUE TITLE
The application display the message "Show error" when review the section of Open Ours

### ISSUE THREAD

**Issue by lesalazar93** [rivetlogic/craftercms-bp-restaurant#11]
Device
Windows	Version
Chrome	        64.0.3282.119
Mozilla	        58.0.1 
IE	                11.125.16299.0

Mac	                Version
Safari	        9.1.2

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1.Open the Bluedprint http://restaurant.c3blueprintsdemo.vm2.rivetlogic.com/
2. Go to the section "Open Ours"

CURRENT RESULT: 
==================== 
The application display the message "Show error"

EXPECTED RESULT: 
==================== 
The application displays right ours for each day
![2 1](https://user-images.githubusercontent.com/33267935/35699423-aa56d61e-0755-11e8-9e25-aadbc576228c.png)

**Comment by Lara89** [comment]
Fixed

<img width="1626" alt="screen shot 2018-02-05 at 10 51 59 am" src="https://user-images.githubusercontent.com/4069946/35817316-a7526464-0a62-11e8-9efc-38f813a4ebf2.png">

**Comment by lesalazar93** [comment]
Tested
