### ISSUE TITLE
The site is not displaying the main content background image, when the background image is too big.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-restaurant#4]
Description: The site is not displaying the main content background image, when the background image is too big.

-Env:
Device: MacBook Pro
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mozilla Firefox 55.0.3 (64-bit)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Zentro Restaurant blueprint.
2. Click on the sidebar to display the menu.
3. On the pages section, click on the edit button of the home page.
4. Go to the main content section and add a big background image (use the "sample image" attached as example)
5. Go to the preview and check the main content background image.

CURRENT RESULT: 
==================== 
The site is not displaying the main content background image, when the background image is too big.
![main content background image bug](https://user-images.githubusercontent.com/28119220/31200928-f1ef5482-a919-11e7-8515-a455ed41e2be.png)

EXPECTED RESULT: 
==================== 
The site should displayed the main content background image, when the background image is too big or the selector should have an option to cut and edit the big image.

Sample image
![sample image](https://user-images.githubusercontent.com/28119220/31200929-f1f1a76e-a919-11e7-9b16-92af4f14d982.jpg)

**Comment by Lara89** [comment]
This has being tested and is working good. Unable to reproduce.

**Comment by lesalazar93** [comment]
Tested in local environment (the bugs can't be reproduced)
