### ISSUE TITLE
The “dish name” is not displayed properly when the name is too long.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-restaurant#5]
Description: The “dish name” is not displayed properly when the name is too long.
-Env:
Device: MacBook Pro
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mozilla Firefox 55.0.3 (64-bit)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Zentro Restaurant blueprint.
2. Click on the sidebar to display the menu.
3. Expand the component section.
4. On the pages section, click on the edit button of the Food Gallery.
5. Go to the content section and type a 50 characters “Dish Name”
5. Go to the preview and check food gallery.

CURRENT RESULT: 
==================== 
Title: The “dish name” is not displayed properly when the name is too long.
![food gallery bug](https://user-images.githubusercontent.com/28119220/31202775-3af2f9b6-a921-11e7-8eec-8c107d35f892.png)

EXPECTED RESULT: 
==================== 
Title: The “dish name” should be displayed properly when the name contains the maximum characters length.

**Comment by lesalazar93** [comment]
The bug is still present problems when use 50 characters in "Dish Ingredients"

**Comment by lesalazar93** [comment]
Tested
