### ISSUE TITLE
The “Food Gallery” is not displayed properly arranged when the user adds a new “Dish”.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-restaurant#6]
Description: When the user adds a new “dish” to the food gallery, the food gallery does not arrange properly the images.

-Env:
Device: MacBook Pro
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mozilla Firefox 55.0.3 (64-bit)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Zentro Restaurant blueprint.
2. Click on the sidebar to display the menu.
3. Expand the component section.
4. On the pages section, click on the edit button of the Food Gallery.
5. Go to the content section and Click on the “Add another” button.
7. Fill out all the fields and add an  image.
7. Click on the “save and close” button
6. Go to the preview and check food gallery.

CURRENT RESULT: 
==================== 
The “Food Gallery” is not displayed properly arranged when the user adds a new “Dish”.
![dishes bug](https://user-images.githubusercontent.com/28119220/31204262-3d752e3c-a928-11e7-89e3-39596156000b.png)

EXPECTED RESULT: 
==================== 
The “Food Gallery” should be displayed properly arranged when the user adds new “Dishes”.

**Comment by lesalazar93** [comment]
Tested in local environment (Need to talk about the actual structure when add dishes )
