### ISSUE TITLE
The send button in the “Contact Us” section is redirecting to an invalid page when the form is send.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-restaurant#8]
Description: The send button in the “Contact Us” section is redirecting to an invalid page when the form is send.

-Env:
Device: MacBook Pro
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mozilla Firefox 55.0.3 (64-bit)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Zentro Restaurant blueprint.
2. Go to the preview of the site.
3. Go to the “Contact Us” section.
4.Fill out all the fields of the “Contact Us” section.
5 Click on the “send” button.

CURRENT RESULT: 
==================== 
The send button in the “Contact Us” section is redirecting to an invalid page when the form is send.
https://www.screencast.com/t/PPIOVzDgxlsX 

EXPECTED RESULT: 
==================== 
The send button in the “Contact Us” section should not redirect to an invalid page when the form is send. An successfull message should be displayed in the same site and all the fields should be cleaned.

*Note this example:
https://www.screencast.com/t/kHYLhibn

**Comment by lesalazar93** [comment]
The bug is still present when completed the required spaces and click in the button "Send".
(Now the bug is : the application don't make any action when complete the required spaces and click on the button "send"

**Comment by lesalazar93** [comment]
Teste in the "live" environment
