### ISSUE TITLE
The site allows the user to expand the “Message” textbox in the “contact us” section, causing that the site is not displayed properly.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-restaurant#9]
Description: The site allows the user to expand the “Message” textbox in the “contact us” section, causing that the site is not displayed properly.

-Env:
Device: MacBook Pro
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Mozilla Firefox 55.0.3 (64-bit)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Zentro Restaurant blueprint.
2. Go to the preview of the site.
3. Go to the “Contact Us” section.
4.Fill out all the fields of the “Contact Us” section.
5 Resize the “Message” textbox

CURRENT RESULT: 
==================== 
The site allows the user to expand the “Message” textbox in the “contact us” section, causing that the site is not displayed properly.
![contact us bug](https://user-images.githubusercontent.com/28119220/31207116-75bdc68a-a939-11e7-8760-6ed7fdfc706d.png)

EXPECTED RESULT: 
==================== 
The site should allows the user to expand the “Message” textbox in the “contact us” section, but it should have a limit of size and then add a scroll bar.

**Comment by lesalazar93** [comment]
Tested in local environment
